language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.18.0

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt clippy
      script:
        - cargo fmt -v -- --check
        - cargo clippy -v -- -D clippy::all
  fast_finish: true

notifications:
  email:
    on_success: never
